### ISSUE TITLE
Is there a way to get an iterator with all timezones?

### ISSUE THREAD

**Issue by lizmat** [alabamenhu/TimezonesZoneInfo#1]
Not really an issue per se, but I wasn't able to glean that from the documentation.

**Comment by alabamenhu** [comment]
> Not really an issue per se, but I wasn't able to glean that from the documentation.

Actually, it *is* an issue, in that `ZoneInfo` is still using my [older (badder) form of resources detection](https://github.com/alabamenhu/TimezonesZoneInfo/blob/cc82293b00da6de031ca326098939ddc88f85f9d/lib/Timezones/ZoneInfo.rakumod#L14). 

I should change this to the way that I do now in `Intl::CLDR`, where the generating script creates a list of all possible IDs, and slurps them into a `Set` with a quick/easy `:exists` check on them.

Obtaining an iterable of sorts would be fairly easy especially since it'd probably just expositing an internal var.  Something like 

    sub timezone-list (
        Bool :$aliases = False, 
        Bool :$historical = False
        --> Positional) 
    { ... }

The only question might be whether it's better to return an `Associative` or a `Positional`. I think the former is more useful, plus internally it'll be stored as one so no coercion penalty, but `timezone-list` is just such a natural routine name :-)

**Comment by lizmat** [comment]
The reason I was asking, was to add support for searching timezones to App::Rak  :-)

**Comment by alabamenhu** [comment]
This has been added with version 0.3.0

**Comment by lizmat** [comment]
> This provides a list of all timezone identifiers as a set (if you need it as a list, .keys). By default it only

Feels like there's something missing?  :-)
